{{- if .Values.ner.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rag-platform.fullname" . }}-ner-cache
  labels:
    {{- include "rag-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ner-service
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ner.persistence.size | quote }}
{{- end }}
