apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-platform.fullname" . }}-ollama-main
  labels:
    {{- include "rag-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama-main
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rag-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama-main
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-platform.fullname" . }}-ollama-judge
  labels:
    {{- include "rag-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama-judge
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rag-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama-judge
